[project]
name = "mcp-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "langchain>=1.0.5",
    "langchain-anthropic>=1.0.2",
    "langchain-mcp-adapters>=0.1.12",
]
